In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd

2026-05-23 23:06:22.163850: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
with open('geography_ohe.pkl', 'rb') as f:
    geography_ohe = pickle.load(f)

In [4]:
with open('gender_le.pkl', 'rb') as f:
    gender_le = pickle.load(f)

In [5]:
with open('ss.pkl', 'rb') as f:
    ss = pickle.load(f)

In [6]:
input_data = {
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [7]:
geography = geography_ohe.transform([[input_data['Geography']]]).toarray()
geo_col = geography_ohe.get_feature_names_out(['Geography'])
df_geography = pd.DataFrame(geography, columns=geo_col)

/Users/tabindahasif/Downloads/ANN Project/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [8]:
df_geography

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [9]:
input_data_df = pd.DataFrame([input_data])

In [10]:
input_data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [11]:
input_data_df.drop(['Geography'], axis=1, inplace=True)

In [12]:
input_data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,Male,40,3,60000,2,1,1,50000

In [13]:
input_data_df = pd.concat([input_data_df,df_geography],axis=1)

In [14]:
input_data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [15]:
gen = gender_le.transform(input_data_df['Gender'])
gen

array([1])

In [16]:
input_data_df['Gender'] = gen
input_data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [20]:
input_scaled = ss.transform(input_data_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [21]:
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

array([[0.02859791]], dtype=float32)

In [22]:
prediction_probablity = prediction[0][0]

In [23]:
if prediction_probablity>0.5:
    print("Customer is likely to churn.")
else:
    print("Customer is not likely to churn.")

Customer is not likely to churn